/* Automatically generated by './build/bin/build-entry.js' */
import testList from '../packages/list/index.js'

import packageInfo from '../package.json'

const components = [
  testList
];

const install = function(Vue, opts = {}) {
  
  components.forEach(component => {
    Vue.component(component.name, component);
  });
  Vue.prototype.$axios = opts.axios

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: packageInfo.version,
  install,
  //单独导出，单独引用的时候用到
  testList
};
